--found mistake or missing translation? go to http://wow.curseforge.com/addons/symbiosis/localization/ to fix it.
Symbiosis.LocalsTable["KOKR"] = setmetatable(
{
	-- ["10manGroup"] = "",
	-- ["10manInstance"] = "",
	-- ["10manInstanceHc"] = "",
	-- ["25manGroup"] = "",
	-- ["25manInstance"] = "",
	-- ["25manInstanceHc"] = "",
	-- ["40manGroup"] = "",
	-- ["40manInstance"] = "",
	-- ["5manGroup"] = "",
	-- ["5manInstance"] = "",
	-- ["5manInstanceHc"] = "",
	AddonDidNotLoadup = "이 애드온은 플레이어가 드루이드여야 동작합니다.",
	AddSpellsGet = "당신에게 주문을 부여합니다.",
	AddSpellsGranted = "대상에게 주문을 부여합니다.", -- Needs review
	Affliction = "고통",
	AllDPSGainSame = "모든 직업의 DPS특성은 같은 주문을 얻습니다.",
	Arcane = "비전",
	Arena = "투기장",
	Arms = "무기",
	Assassination = "암살",
	-- AutomationOff = "",
	Background = "배경",
	BackgroundName = "배경이름",
	Battleground = "전장",
	BeastMastery = "야수",
	Blood = "혈기",
	Brewmaster = "양조",
	Buffed = "Buffed", -- Needs review
	BuffIsUp = "공생 시전됨",
	BuffNotUp = "공생 시전 안됨",
	ButtonConfig = "버튼설정",
	CannotChangeTargetInCombat = "대상이 전투중일때는 공생을 변경할 수 없습니다.",
	-- CannotToggleInCombat = "",
	-- ChallengeMode = "",
	ChangeSize = "크기 변경",
	ChangeSizeButton = "공생 버튼 크기 변경",
	ClickedForFirstTime = "첫번째에는 공생 버튼을 클릭해야 합니다.", -- Needs review
	Combat = "전투",
	ConfirmResetButtonPos = "공생 버튼의 위치를 초기화",
	ConfirmResetMacro = "To reset macro code type the following:", -- Needs review
	Dead = "사망",
	Demonology = "악마",
	Destruction = "파괴",
	-- Disabled = "",
	DisableShiftClick = "Disable shift-left-click on Symbiosis button", -- Needs review
	DisableShiftClickTooltip = "A shift-left-click on the Symbiosis button removes the current Symbiosis buff.", -- Needs review
	DisableWhispArena = "투기장에서 귓속말을 비활성화",
	Discipline = "수양",
	Disconnect_Short = "d/c", -- Needs review
	Done = "완료",
	DontRemoveTarget = "대상이 공격대를 탈퇴해도 대상을 삭제하지 않습니다.",
	DontRemoveTargetTooltip = "You wont be able to cast Symbiosis on selected target unless target rejoins raid. This option may be usefull for arena/battleground groups.", -- Needs review
	DontShowTaggedAs = "Don't show untis tagged as...", -- Needs review
	DraggingEnabled = "Dragging enabled. To stop dragging hit the 'Stop Drag' button or type the following:", -- Needs review
	DraggingStopped = "드래그가 중단되었습니다.",
	Elemental = "정기",
	-- Enabled = "",
	EnableDisableDragging = "공생 버튼의 드래그 활성화 / 비활성화",
	EnableTargetWhisper = "대상에게 귓속말 활성화",
	Enhancement = "고양",
	Feral = "야성",
	FilterRemovedAll = "당신의 필터가 모든 대상을 제거했습니다.",
	Fire = "화염",
	FirstLoginMessage = "이 애드온을 켠 후 첫번째 로그인 입니다. 공생 버튼을 당신이 원하는 위치로 드래그 한 후 '드래그 중지' 버튼을 클릭하세요.", -- Needs review
	Frost = "냉기",
	FullWhispOnlyOnFirst = "Full whisper message only on first whisper", -- Needs review
	FullWhispOnlyOnFirstTooltip = "On consecutives whispers only a simplified message will be send.", -- Needs review
	Fury = "분노",
	Guardian = "수호",
	-- HeaderSpellGet = "",
	-- HeaderSpellGrant = "",
	-- HeaderText = "",
	Holy = "신성",
	-- IgnoredUnchecked = "",
	-- IgnoreShowHide = "",
	-- IgnoreShowHideTooltip = "",
	InCombat = "당신은 전투중 입니다.",
	InInsignificantGroup = "파티가 아닙니다.",
	InInsignificantGroupTooltip = "이 옵션을 활성화하면 총 25명의 5파티를 기준으로 배열됩니다. 총 8개의 파티를 보려면 이 옵션을 해제하세요.",
	-- InParty = "",
	-- InRaid = "",
	IsNowHidden = "공생 버튼이 숨겨져 있습니다.",
	IsNowVisible = "공생 버튼이 이제 표시됩니다.",
	KeyBindingname = "Simulate Click on Symbiosis button", -- Needs review
	ListOfSpellsGet = "이것은 당신이 대상에게 공생을 시전했을 때 당신이 얻을 수 있는 주문의 목록입니다.",
	ListOfSpellsGrant = "이것은 당신이 대상에게 공생을 시전했을 때 다른 플레이어가 얻을 수 있는 주문의 목록입니다.",
	LongMacroHint1 = "이 애드온은 당신의 단축키에 적용할 수 있는 단축키를 제공합니다.",
	LongMacroHint2 = "당신은 매번 지정된 키를 누르면 공생이 시전 될 것입니다.",
	LongMacroHint3 = "You can edit that macro only here.", -- Needs review
	LongMacroHint4 = "Use the following dummy for your Symbiosis target, everytime you select a new Symbiosis target the macro will be updated automatically:", -- Needs review
	LongMacroHint5 = "So the following example line will always cast Symbiosis on your selected target:", -- Needs review
	LongMacroHint6 = "You should always include the following script, which handles some whisper stuff and displays the cooldown of Symbiosis:", -- Needs review
	LongMacroHint7 = "Note: If you don't have selected a Symbiosis target or the Symbiosis buff is up, all instances of '[@SYMB]' will be removed from the macro. If you have selected a Symbiosis target the dummy 'SYMB' will be replaced by the target then.", -- Needs review
	LongPopUpHint1 = "You can change the background art of the popup menu here. Just click on a tile to select it.", -- Needs review
	LongPopUpHint2 = "You can even add your own textures, look for the HowToAddOwnTextures.txt in the 'media' folder of the Symbiosis directory on how to do that.", -- Needs review
	LongWhisperHint = "When you cast Symbiosis your target may receive a whisper from you with this option. Delay between two whispers is 1 minute, to prevent spam.", -- Needs review
	Macro = "매크로",
	MacroOptions = "macro options (for advanced users)", -- Needs review
	MacroOptions_Short = "Macro (adv.)", -- Needs review
	MacroRestored = "Macro was restored to standard.", -- Needs review
	Marksmanship = "사격",
	Minutes_Short = "최소",
	Mistweaver = "운무",
	Moonkin = "조화",
	NoTarget = "대상없음",
	NoTargetFound = "대상이 없습니다.",
	NotEnoughMacroSpace = "새로운 캐릭터 매크로를 만들만 한 공간이 부족합니다. 매크로를 삭제하거나 UI를 재시작한 후 재시도 하세요.",
	NotInParty = "파티가 아닙니다.",
	NotInRaid = "공격대가 아닙니다.",
	Offline = "오프라인",
	Options = "옵션",
	Outside = "외부",
	OutsideTooltip = "인스턴스 던전이 아닌곳은 모두 바깥으로 간주됩니다.",
	PopUp = "팝업",
	PopUpOptions = "팝업옵션",
	PrintMessageWhenTarLeaves = "공생 대상이 공격대를 떠날 때 메세지를 출력합니다.",
	Protection = "방어",
	-- Raidfinder = "",
	-- RdyCheckWarn = "",
	RemovedBuff = "당신이 공생버튼을 쉬프트 좌클릭하면 공생 버프가 제거됩니다.",
	RemoveNoTargetTag = "대상없음 태그를 제거",
	RemoveNoTargetTagTooltip = "Hides the 'No Target' tag above the Symbiosis button when no target is selected.", -- Needs review
	Reset = "초기화",
	ResetMacro = "매크로초기화",
	ResetPosition_Short = "포지션 초기화",
	ResetPositionTooltip = "툴팁위치초기화",
	Resto = "Resto", -- Needs review
	Restoration = "회복",
	Retribution = "징벌",
	Seconds_Short = "Sec", -- Needs review
	SelectBackground = "배경 선택",
	Shadow = "암흑",
	ShowGCD = "GCD 보임",
	ShowGCDTooltip = "GCD 툴팁 보임",
	-- ShowHeader = "",
	-- ShowHeaderTooltip = "",
	-- ShowHide = "",
	-- ShowHideOptions = "",
	Size = "크기",
	-- Solo = "",
	SpellGrantDepends = "대상이 얻는 주문은 당신의 특성이 아니라 그들의 특성에 따라 달라집니다.",
	SpellsGet = "주문 얻음",
	SpellsGrant = "주문 얻음",
	SpellYouGetDepends = "당신이 얻는 주문은 대상의 특성이 아니라 당신의 특성에 따라 달라집니다.",
	StartDrag = "드래그 시작",
	Stolen = "Stolen", -- Needs review
	StopDrag = "드래그 중지",
	Subtlety = "잠행",
	Survival = "생존",
	TargetConfig = "대상설정",
	TargetLeftParty = "당신의 공생 대상이 파티를 떠났습니다.",
	TargetRemoved = "대상 초기화",
	TargetStolen = "Target stolen", -- Needs review
	TestMessage = "테스트 메세지",
	ToOpenOptUse = "To open the option menu use", -- Needs review
	Transparency = "투명도",
	-- TriStateTooltip = "",
	Unholy = "부정",
	UnitHasOther = "대상은 다른 드루이드의 공생을 받았습니다.",
	UnknownCommand = "유효하지 않은 명령어",
	-- WarnOnRdyCheck = "",
	-- WarnOnRdyCheckTooltip = "",
	Welcome = "Welcome",
	WelcomeBack = "Enabled. Welcome back", -- Needs review
	Whisper = "귓속말",
	WhisperOptions = "귓속말 옵션",
	-- WillHide = "",
	-- WillIgnore = "",
	-- WillShow = "",
	Windwalker = "풍운",
	YouDontKnowSymbiosis = "공생 주문을 배우지 않았습니다.",
	YouGrantedMe = "드루이드는 다음 주문을 얻습니다 %s.", -- Needs review
	YouHaveSymbiosis = "당신은 %s을 받았습니다!", -- Needs review
	YoullGet = "당신은 다음 주문을 얻습니다 %s.", -- Needs review
}
, {__index = Symbiosis.LocalsTable["ENUS"]});